# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OjoMetropolitano' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OjoMetropolitano
pod 'couchbase-lite-ios', '~> 1.4.1'
pod 'Firebase/Core'
pod 'Firebase/Messaging'

  target 'OjoMetropolitanoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OjoMetropolitanoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
